### ISSUE TITLE
@import "global.import.css 无效啊！

### ISSUE THREAD

**Issue by s5s5** [hanan198501/ReRes#10]
CSS中有import时 `@import "global.import.css";` 无法代理 global.import.css 啊！！！

**Comment by hanan198501** [comment]
看看请求的规则有没有命中

**Comment by s5s5** [comment]
有命中啊~~~
CSS都是同级放啊

**Comment by hanan198501** [comment]
看看 network 中的请求 url

**Comment by s5s5** [comment]
是我没说清楚重现的情况，SORRY~~~
是这样，线上的 `http://tool.misuisui.com/style/`路径指向 `http://localhost:63342/htdocs/style0/`时就会有这种问题出现~~~
`http://localhost:63342` 这样的地址是用 WebStorm 这个工具预览时生成的。

**Comment by s5s5** [comment]
另外再反馈一个问题，就是当我把所有规则都不启用，但每次 Chrome 重起后，再打开 ResRes 总会有最后一个规则被打上勾

**Comment by hanan198501** [comment]
我测试是可以的，是不是你正则没写对？
If URL match: ^http\:\/\/tool\.misuisui\.com\/style\/$
Response: http://localhost:63342/htdocs/style0/

**Comment by s5s5** [comment]
还要用正则啊……我都是直接写网址……
