### ISSUE TITLE
没效果

### ISSUE THREAD

**Issue by yyman001** [hanan198501/ReRes#7]
难道是我打开方式不对?
没有详细的demo?
怎么指向本地文件夹里面的文件?

**Comment by hanan198501** [comment]
以file://开头就是指向本地文件。

**Comment by yyman001** [comment]
虽然是替换了,但样式好像不生效- -郁闷

**Comment by plh97** [comment]
醉了, 原来file://开头就是本地文件协议
我特意开了个本地服务器 http://localhsot/dist
eeeeeee
